export const GET_ALLCATEGORY = "GET_ALLCATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const SUBCATEGORY_ERROR = "SUBCATEGORY_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
